[package]
name = "optpipeline"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
is-terminal = "0.4.13"
itertools = "0.12.1"
pager = "0.16.1"
regex = "1.10.4"
tempfile = "3"
