[package]
name = "optpipeline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.1"
pager = "0.16.1"
regex = "1.10.4"
tempfile = "3"
