[package]
name = "optpipeline"
version = "0.2.1"
edition = "2021"
license = "BSD-2-Clause"
description = "A CLI tool that displays diffs of LLVM IR changes between optimization passes"
repository = "https://github.com/abrasumente233/op"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
is-terminal = "0.4.13"
itertools = "0.12.1"
pager = "0.16.1"
regex = "1.10.4"
tempfile = "3"

[package.metadata.release]
publish = false
